export const data = [
  {
    id: 0,
    name: "Vegetable Biryani",
    type: 0,
    description: "Leo vel orci porta non pulvinar neque laoreet. ",
    price: [89],
    category: "Biryani",
  },
  {
    id: 1,
    name: "Chicken Biryani",
    type: 2,
    description: "Pellentesque id nibh tortor id aliquet lectus.",
    price: [149],
    category: "Biryani",
  },
  {
    id: 2,
    name: "Lamb Biryani",
    type: 2,
    description: "Pellentesque id nibh tortor id aliquet lectus.",
    price: [169],
    category: "Biryani",
  },
  {
    id: 3,
    name: "Egg Roll",
    type: 1,
    price: [25, 35],
    category: "Roll",
  },
  {
    id: 4,
    name: "Paneer Roll",
    type: 0,
    price: [35, 45],
    category: "Roll",
  },
  {
    id: 5,
    name: "Chimken Roll",
    type: 2,
    price: [45, 75, 125],
    category: "Roll",
  },
  {
    id: 6,
    name: "Noodles Roll",
    type: 0,
    price: [25, 35],
    category: "Roll",
  },
  {
    id: 7,
    name: "Schezwan Roll",
    type: 2,
    price: [45],
    category: "Roll",
  },
  {
    id: 8,
    name: "Egg Cheese Roll",
    type: 1,
    price: [65],
    category: "Roll",
  },
  {
    id: 9,
    name: "Malai Kofta",
    type: 0,
    description:
      "Leo vel orci porta non pulvinar neque laoreet. Sed blandit libero volutpat sed. Eu volutpat odio facilisis mauris. Pellentesque id nibh tortor id aliquet lectus.",
    price: [149],
    category: "MAIN COURSE",
  },
  {
    id: 10,
    name: "Chole Curry",
    type: 0,
    description:
      "Leo vel orci porta non pulvinar neque laoreet. Sed blandit libero volutpat sed. Eu volutpat odio facilisis mauris. Pellentesque id nibh tortor id aliquet lectus.",
    price: [165],
    category: "MAIN COURSE",
  },
  {
    id: 11,
    name: "Murgh Mussallam (4 pcs.)",
    type: 2,
    description:
      "Leo vel orci porta non pulvinar neque laoreet. Sed blandit libero volutpat sed. Eu volutpat odio facilisis mauris. Pellentesque id nibh tortor id aliquet lectus.",
    price: [275],
    category: "MAIN COURSE",
  },
  {
    id: 12,
    name: "Palak Paneer",
    type: 0,
    description:
      "Leo vel orci porta non pulvinar neque laoreet. Sed blandit libero volutpat sed. Eu volutpat odio facilisis mauris. Pellentesque id nibh tortor id aliquet lectus.",
    price: [175],
    category: "MAIN COURSE",
  },
  {
    id: 13,
    name: "Egg Curry",
    type: 1,
    description:
      "Leo vel orci porta non pulvinar neque laoreet. Sed blandit libero volutpat sed. Eu volutpat odio facilisis mauris. Pellentesque id nibh tortor id aliquet lectus.",
    price: [165],
    category: "MAIN COURSE",
  },
];
